# Generated by Django 4.2.16 on 2026-06-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        ('bookings', '0001_initial'),
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinbooking',
            name='services',
            field=models.ManyToManyField(blank=True, to='salons.service'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='barbers.barber'),
        ),
        migrations.AddField(
            model_name='booking',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='barbers.barber'),
        ),
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salons.branch'),
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salons.coupon'),
        ),
    ]
