# Generated by Django 4.2.16 on 2026-06-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_15m_sent',
            field=models.BooleanField(default=False),
        ),
    ]
