# Generated by Django 4.2.16 on 2026-06-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('target', models.CharField(choices=[('all', 'Hammasi'), ('customers', 'Mijozlar'), ('barbers', 'Sartaroshlar')], default='all', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('total_sent', models.IntegerField(default=0)),
                ('is_sent', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ommaviy bildirishnoma',
                'verbose_name_plural': 'Ommaviy bildirishnomalar',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_uz', models.CharField(blank=True, max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('body_uz', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('booking', 'Bron'), ('reminder', 'Eslatma'), ('promotion', 'Aksiya'), ('system', 'Tizim'), ('review', 'Sharh')], default='system', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
