# Generated by Django 4.2.16 on 2026-06-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barbers', '0001_initial'),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebarber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_barbers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customernote',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to='barbers.barber'),
        ),
        migrations.AddField(
            model_name='customernote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barberportfolio',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='barbers.barber'),
        ),
        migrations.AddField(
            model_name='barberportfolio',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salons.service'),
        ),
        migrations.AddField(
            model_name='barber',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbers', to='salons.branch'),
        ),
        migrations.AddField(
            model_name='barber',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbers', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='barbers', to='salons.service'),
        ),
        migrations.AddField(
            model_name='barber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favoritebarber',
            unique_together={('user', 'barber')},
        ),
        migrations.AlterUniqueTogether(
            name='customernote',
            unique_together={('barber', 'customer')},
        ),
    ]
