# Generated by Django 4.2.16 on 2026-06-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_barber_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/covers/'),
        ),
    ]
