# Generated by Django 4.2.16 on 2026-06-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0006_barberportfolio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberportfolio',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20),
        ),
    ]
