# Generated by Django 4.2.16 on 2026-06-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_workinghours_break'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkaklar'), ('female', 'Ayollar'), ('unisex', 'Umumiy')], default='unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/'),
        ),
    ]
