# Generated by Django 4.2.16 on 2026-06-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_category_gender_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkaklar uchun'), ('female', 'Ayollar uchun'), ('unisex', 'Hammasi uchun')], default='unisex', max_length=10),
        ),
    ]
